import { Router } from "express";
import { verifyJWT } from "../middlewares/auth.middleware";
import { verifyUser } from "../middlewares/user-verify.middleware";
import { upload } from "../middlewares/multer.middleware";
import { createProduct, deleteProduct, getAllProducts, getMyProducts, getProductById, updateProduct } from "../controllers/product.controller";
const router = Router();
router.get("/", getAllProducts);
router.post("/create", verifyJWT, verifyUser, upload.single("productImage"), createProduct);
router.get("/my-products", verifyJWT, verifyUser, getMyProducts);
router.get("/get/:id", verifyJWT, getProductById);
router.delete("/delete-product/:productId", verifyJWT, verifyUser, deleteProduct);
router.patch("/update/:productId", verifyJWT, verifyUser, upload.single("imagePath"), updateProduct);
export default router;
